kind: pipeline
name: default

steps:
- name: test
  image: postgres:9-alpine
  commands:
  - psql -U postgres -d test -h database

services:
- name: database
  image: postgres:9-alpine
  environment:
    POSTGRES_USER: postgres
    POSTGRES_DB: test
