kind: pipeline
name: default

steps:
- name: build
  image: golang:1.13
  commands:
  - make build_linux_amd64

- name: docker
  image: plugins/docker
  settings:
    registry: hub.docker.com
    repo: hub.docker.com/dbaupload0031/demo
    auto_tag: true
    auto_tag_suffix: linux-amd64
    username: dbaupload0031
    password:
      from_secret: dsf5572a
