kind: pipeline
type: docker
name: build
steps:
- name: build-code
  image: golang:alpine
  pull: if-not-exists # always never
  commands:
    - go build server.go
- name: build-image
  image: plugins/docker
  settings:
    repo: dbaupload0031/201901
    auto_tag: true
    use_cache: true
    username:
      from_secret: dockerhub_usr
    password:
      from_secret: dockerhub_pwd
    tags: ${DRONE_BUILD_NUMBER}
    insecure: true
trigger:
  branch:
  - master
  event:
  - push
